# Site settings
title: Synthetic Labor
email: contact@massivewaves.com
url: https://massivewaves.github.io/syntheticlabor
description: "Uncover the secrets buried deep within a biotech facility. Navigate deadly creatures, solve puzzles, and fight to survive in this gripping story-driven adventure."

color:
  primary-dark: '#1C1C1C'
  links: '#ff6b6b'

# Footer settings
footer: Massive Waves

social:
  - title: youtube
    url:
  - title: twitter
    url:
  - title: instagram
    url:

header-bg: img/sl5.png
wishlist-bg: img/sl4.png

images:
  - src: img/sl1.png
  - src: img/sl2.png
  - src: img/sl3.png


# Build settings
markdown: kramdown
permalink: pretty
